version: '3.1'
services:
  db:
    image: mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=storage
    volumes:
      - ./db:/var/lib/mysql

  storage:
    build: .
    restart: always
    ports:
      - 5001:5001
    links:
      - db
    volumes:
      - ./logs:/usr/src/app/logs
      - ./storage:/usr/src/app/storage
